### ISSUE TITLE
スクロールの軽量化

### ISSUE THREAD

**Issue by totegamma** [totegamma/concurrent-world#107]
今はreact-infinite-scrollerを使って無限に新しく要素を追加していく感じで無限スクロールを実装しているが、やっぱり下の方にいくと重くなる。
react-virtualized, react-virtuoso等を使って軽量化したい。

(前に触ったときは画像がめっちゃ点滅したり、上向きのスクロールの挙動が破滅的(深刻)だったりで結構難しい...

**Comment by totegamma** [comment]
かなり昔のブランチだが https://github.com/totegamma/concurrent-web/tree/feat/virtual-scroll で react-virtualizedを使って実装していた

現在は絵文字ピッカーでreact-virtualizedの後継ライブラリreact-windowを利用しているが、react-windowは可変サイズのスクロールに対応していないっぽい？

**Comment by ouroboros723** [comment]
メモ: 役に立ちそうなライブラリ

- https://github.com/inokawa/virtua
- https://github.com/petyosi/react-virtuoso

**Comment by ouroboros723** [comment]
# 追加情報(わかったことまとめ)
## 重くなる問題の詳細
主にChromeでのみ重くなることが確認された。
- https://concurrent.world/message/eee61a2c-284c-4985-a3fb-38ecb456aa88@CCCb018771C38F0A06c1A5Dd8587887f0DF9a004Fa
- https://concurrent.world/message/43e6454c-7325-4e5e-9a34-d448c866ceb3@CCCb018771C38F0A06c1A5Dd8587887f0DF9a004Fa
- https://concurrent.world/message/8c9609ad-3eab-4f7f-9772-f971094bac19@CCCb018771C38F0A06c1A5Dd8587887f0DF9a004Fa
- https://concurrent.world/message/a58beb38-1b38-415e-b232-bd74d766e422@CCCb018771C38F0A06c1A5Dd8587887f0DF9a004Fa

## 原因について
どうやらConcurrent上で動いているAnimation(特に追加読み込み時のローディングとmarquee要素)の描画が原因となっている模様

- https://concurrent.world/message/85aeae1c-feca-4c91-81bf-49c7b57107ba@CC506dDf8C7d5B0ea9242C699F628756E674E8Af26
- https://concurrent.world/message/6e705a06-db1b-4733-a18c-54a7fb962408@CC506dDf8C7d5B0ea9242C699F628756E674E8Af26
- https://concurrent.world/message/b7564c29-d65b-4464-842e-b3bc25f2624a@CC815Dc27ea15BeD09F01a25606992B3D6E9D64719
- https://concurrent.world/message/0297474d-1f04-4a1a-be7f-c4fb215b0761@CC506dDf8C7d5B0ea9242C699F628756E674E8Af26
- https://concurrent.world/message/5a5db474-8eb3-4c4c-b9cc-f4e133541aaf@CC506dDf8C7d5B0ea9242C699F628756E674E8Af26
- https://concurrent.world/message/0d1c3651-f219-4d8e-8464-286bc03125bc@CC506dDf8C7d5B0ea9242C699F628756E674E8Af26
- https://concurrent.world/message/49320917-82df-42bb-be9e-5e7c8e032b35@CC506dDf8C7d5B0ea9242C699F628756E674E8Af26
- https://concurrent.world/message/73ea732d-b819-4cad-befe-e15f7cadaeda@CCCb018771C38F0A06c1A5Dd8587887f0DF9a004Fa

**Comment by ouroboros723** [comment]
## 考えられる修正方法
- ローディングアイコン・marqueeともに要素が画面外へでたらCSS `display: none` を適用する

**Comment by ouroboros723** [comment]
marqueeの描画時に重くなる問題について議論・修正が完了するまではopenのままでお願いしたいです。

**Comment by totegamma** [comment]
それはそれとしてmarqueeはcssに移行する別issueを立てちゃいますね！

**Comment by ouroboros723** [comment]
@totegamma 
ありがとうございます！
ではmarquee関連はそちらに書き込みますね！
