### ISSUE TITLE
message単体ページを作る

### ISSUE THREAD

**Issue by totegamma** [totegamma/concurrent-world#167]
基本的には
/message/<messageID>
と思うところだが、messageIDを解決するためにはそのmessageを現在保持しているホストを解決する必要がある。
そのホストの解決はauthorのCCAddressで行えるため、完全には
/message/<messageID>@<authorAddr>
となる。

なのだが、 #148 のようなことをメッセージでも実現するために未ログイン時にどのホストで解決するかのホスト名を入れたい。
そうすると、/message/<messageID>@<authorAddr>@<resolveHost> とだんだんヤバい感じになってくる。

ま、でも仕方ないカモ。とりあえずこのリンクにジャンプするようにして、実装的にはmessageIDをresolveHost宛に解決する実装にして、そのうち引っ越し機能などが充実してきたらauthorAddrを解決に使うようにすると良さそう。

**Comment by totegamma** [comment]
大体実装して残りはリプライ周りを充実化させる

**Comment by oinarisummer** [comment]
リプライツリーを表示しようとするとMessagePageの時点でAssociationsを取得する必要がある。
Associationsを取るところはMessagePageから呼び出しているMessageContainerに実装がある。
→ MessageContainer内にまとめられてる機能をコンポーネント化した方が良さそう
