### ISSUE TITLE
ユーザーやストリームの属性でも絵文字を使いたい

### ISSUE THREAD

**Issue by malamutedataro** [totegamma/concurrent-world#238]

**Comment by totegamma** [comment]
軽量なマークダウンレンダラーのようなものがあるといいのかもしれない

**Comment by totegamma** [comment]
asciiなプロフィール名(例えば診断メーカーみたいなアプリと連携した場合とか)を見ると、
hogehoge<img src="https://~~~~/~~~.png">
みたいな感じになるリスクをどのくらい和らげるかがポイントなきがする
