### ISSUE TITLE
streamの削除/アーカイブ機能

### ISSUE THREAD

**Issue by waonme** [totegamma/concurrent-world#239]

**Comment by totegamma** [comment]
アーカイブするとどういう感じになる(削除との違い)イメージですか

**Comment by waonme** [comment]
閲覧は可能で、書き込みや属性の変更が不可の状態になるイメージです。
ストリームの一覧や検索の絞り込みに使えたり、順位の低下にも使えたらいいかと思います。

**Comment by totegamma** [comment]
モチベーションとしては、そのうち見返すかもしれないけれど「自分が作成したストリーム一覧(まだないけど)」からはとりあえず省きたい... みたいな感情になるのかな

ズバッと削除するかそのまま放置でもいい気もする...

**Comment by totegamma** [comment]
話し合いの結果削除機能はちょっとまだ考え中で、アーカイブ機能はstreamをjsonかなにかにサーバーの方でしてしまって、それをダウンロード & ローカル閲覧くらいにしてしまうのが良さそう～

**Comment by totegamma** [comment]
バックエンドの領域なので一旦close
