### ISSUE TITLE
クライアントリセットに今設定してるIDのクレデンシャルを入力させるように

### ISSUE THREAD

**Issue by waonme** [totegamma/concurrent-world#257]
## Problem / 問題点
非常に危険であるログアウト機能の確認が一度しかない
どうしたら秘密鍵のバックアップができるのかがわからない

## Solution (Optional)
2段階で確認を取ると同時に秘密鍵のバックアップを案内する

案
ユーザーが[ログアウト]をクリックする
↓
システムが「再ログインに必要な秘密鍵をログアウト前にバックアップしますか」と尋ねる
「はい」ならバックアップが可能なページに飛ぶか、その場で秘密鍵を表示する
「いいえ」なら次の質問に進む
↓
「ログアウトしますか」と尋ねる
「はい」ならログアウト処理を開始

**Comment by totegamma** [comment]
どちらかというと僕はID生成時みたいに入力してリセットみたいなのの方に1票

**Comment by totegamma** [comment]
なんかアレ、サービスでよくある大事な操作させるときに再度パスワード入れさせるヤツと同じノリでいいかも

**Comment by waonme** [comment]
そういえばボイチャで自分で言ってた（照
