### ISSUE TITLE
秘密鍵の喪失リスクを減らしたい

### ISSUE THREAD

**Issue by waonme** [totegamma/concurrent-world#258]
## What - 提供したい体験
秘密鍵を喪失しない

## Why (Optional)
サービスの利用を開始したい時はさっさと開始したいので登録時は雑にコピペで進められる現状の仕様は嬉しい。
が、そのままバックアップをとり忘れてしまい放置してしまうことがある。
結果、ログアウト以外のタイミング、ブラウザ内のデータの喪失やハードウェアの破損などでアカウントを喪失するリスクがある。

## How - 実装の方針(Optional)
様々なサービスにあるように、メールアドレスの所有者チェックが済んでいないことの通知のようなノリでサービス中にどこかでバックアップの確認があるといいかも？

**Comment by totegamma** [comment]
既存のパスワードマネージャーみたいなのとか、metamaskとかのウォレットを参考にしてみたい
個人的には1passwordみたいにエマージェンシーキット(PDF)をダウンロードさせたり、画像として保存させる等はしてもいいかなぁと思った
