### ISSUE TITLE
投稿先をデフォルト投稿先にリセットする機能

### ISSUE THREAD

**Issue by waonme** [totegamma/concurrent-world#294]
## What - 提供したい体験
気軽にデフォルト投稿先に投稿したい

## How - 実装の方針(Optional)
「下書きを削除」で投稿先もリセットするようにするのがシンプルかも？

**Comment by totegamma** [comment]
今僕が投稿先をワンクリックで変える方法として「下書きを維持したままストリーム切り替えで投稿先が変わる」という今の仕様に依存しきっているので諸々どうしようかなと思っている...
