### ISSUE TITLE
メニュー内のリスト一覧の順番を入れ替えられるようにしたい

### ISSUE THREAD

**Issue by ouroboros723** [totegamma/concurrent-world#345]
## Problem / 問題点
〇 What/Where
メニュー内のリスト一覧の順番を入れ替えられるようにしたい
![image](https://github.com/totegamma/concurrent-web/assets/23020033/b5514eb7-aa50-43bc-a6a4-e7b2f925f39d)

〇 Why
閲覧頻度の高い順に並べたり出来たほうが便利そうなので。

## Solution (Optional)
<How>
リスト一覧の編集設定画面を用意するなど。

**Comment by totegamma** [comment]
muiで並び替えリストが提供されてないので、いい感じのライブラリを探したい......

**Comment by totegamma** [comment]
UIはともかくv1になって並び替え自体はできるようになったので一旦Closeします 🙏
