### ISSUE TITLE
スマホで使用していると段々重くなる

### ISSUE THREAD

**Issue by ouroboros723** [totegamma/concurrent-world#365]
## Problem / 問題点
<What / Where / Why>
◯ What
スマートフォンで長時間Concurrentを使用していると動作が重くなる問題があります。
◯ Where
TL全般
◯ Why
・負荷が増えることでスマートフォンの電池消費が増える、端末が熱くなるなどの問題が起きる
・快適性の低下によるConcurrentへの滞在時間の減少
・更に使い続けると画面のカクツキ、フリーズが発生する

## Solution
<How>
未検証ですが、RAM消費の問題の可能性を疑っています。
まずはTLで画面外に出たコンテンツをunloadする処理を入れて動作が軽くなるか見るのが良いと思います。

◯ 追記
以前からConcurrent上で話題にある問題ですが、同様のIssueが見つけられなかったので起票しました。
もしダブっていたらCloseして下さい🙇💦

**Comment by ouroboros723** [comment]
余裕ができたら取り組んでみます！

**Comment by totegamma** [comment]
大体これがキーかなーと思っています
https://github.com/totegamma/concurrent-web/issues/107

**Comment by ouroboros723** [comment]
> 大体これがキーかなーと思っています
> https://github.com/totegamma/concurrent-web/issues/107

あっ、すみません💦
ありがとうございます...!!!

**Comment by totegamma** [comment]
#107 の解決でだいぶ改善が見られた？ようなので一旦Close
