### ISSUE TITLE
リストに追加ボタンをユーザーページにつける

### ISSUE THREAD

**Issue by totegamma** [totegamma/concurrent-world#368]
今Ackボタンが有るところに[リストに追加 | ▽] って感じメニューボタンをデカく配置して、ユーザーがリストに追加できることに気づきやすくしたい

**Comment by oinarisummer** [comment]
PR#378でリストに追加ボタンが付いたけど、ヘッダーにもリストに追加ボタンが残り続けている
![image](https://github.com/totegamma/concurrent-web/assets/13503779/0a2513a8-bbd8-419b-ad6e-e6ff0a3af359)
