### ISSUE TITLE
Korean translation

### ISSUE THREAD

**Issue by alternative00** [totegamma/concurrent-world#370]
## What - 提供したい体験
Korean translation for Concurrent

## Why (Optional)
for korean user like me

## How - 実装の方針(Optional)
me(i know nothing about japanese) and other koreans(not sure), using translators(deepl, papago, google translator etc.)

**Comment by alternative00** [comment]
so can i help this?

**Comment by totegamma** [comment]
thank you for having interest!
we are working on #347 and it will import i18n system. once locale system created, creating locale variation would be easier so could you wait until #347 completed?

**Comment by alternative00** [comment]
Thanks!
