### ISSUE TITLE
投稿を削除した後ログインせずにプロフィールを開くとdevModeが無く描写で問題が起きる

### ISSUE THREAD

**Issue by yupix** [totegamma/concurrent-world#372]
## Expected Behaviour / 期待した挙動

Message not found と表示される

## Actural Behavior / 実際の挙動

エラーが表示される

<img width="515" alt="image" src="https://github.com/totegamma/concurrent-web/assets/50538210/7f350d29-54f5-4a3e-8a15-c486b4f50bde">

## Steps to Reproduce / 再現方法

1. 投稿する
2. 投稿を削除する
3. プライベートウィンドウを開き、プロフィールを開く
4. 該当する投稿の箇所がエラーになる

## Additional Information / 追加情報

OS: Windows 11 Pro Insider Preview 23545.1000
Microsoft Edge(117.0.2045.31 )

<img width="515" alt="image" src="https://github.com/totegamma/concurrent-web/assets/50538210/7f350d29-54f5-4a3e-8a15-c486b4f50bde">

Firefox(117.0.1)

<img width="615" alt="image" src="https://github.com/totegamma/concurrent-web/assets/50538210/e5a367bc-83e4-4db9-a10a-f8f3fa5e9187">

関係ありそうなコード:

https://github.com/totegamma/concurrent-web/blob/6e401c63f1006d97854db3aa5e425cd5d9e85164/src/components/Message/MessageContainer.tsx#L164

**Comment by totegamma** [comment]
🙏
