### ISSUE TITLE
TL中のCCAvatarのツールチップ内にあるフォローボタンの動作が変

### ISSUE THREAD

**Issue by oinarisummer** [totegamma/concurrent-world#380]
かつてフォローだった機能が今はリストへの追加になった。
ボタンを押した後にリストを選択するポップアップがツールチップと噛み合っていない。

どうすべきかも含めて要検討？

**Comment by totegamma** [comment]
とりあえず 216f82cd03b27ec43fa30d422550d109e13fcafa でmenuのzIndexをtooltip+1にして解決
